"""added expire_at

Revision ID: dd35b08a4474
Revises: 8e2132de6e4f
Create Date: 2023-08-25 14:28:36.641934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd35b08a4474'
down_revision: Union[str, None] = '8e2132de6e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Email_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expire_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Email_verification', schema=None) as batch_op:
        batch_op.drop_column('expire_at')

    # ### end Alembic commands ###
